version: '3.1'

services:
  mongodb-service:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    env_file:
      - .env
    networks:
      backend: null
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d

  mongo-express-service:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb-service:27017/Todo?authSource=admin
    env_file:
      - .env
    networks:
      backend: null
  farm-backend-service:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:  
      - mongodb-service    
    networks:
      backend: null
    restart: always
    volumes:
      - './backend:/code'
  farm-frontend-service:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:  
      - farm-backend-service    
    networks:
      backend: null
    restart: always

networks:
  backend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.17.0/24 